# Generated by Django 3.2.8 on 2021-12-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Accesorio', max_length=120)),
                ('cantidad', models.IntegerField(help_text='Cantidad de Accesorios', max_length=120)),
                ('valor', models.IntegerField(help_text='Valor del Accesorio', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la Mascota', max_length=120)),
                ('raza', models.CharField(help_text='Raza de la MAscota', max_length=120)),
                ('edad', models.IntegerField(help_text='Edad de la MAscota', max_length=120)),
            ],
        ),
    ]
