# Generated by Django 3.2.8 on 2021-12-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios',
            name='valor',
            field=models.FloatField(help_text='Valor del Accesorio', max_length=120),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='edad',
            field=models.IntegerField(help_text='Edad de la Mascota', max_length=120),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='raza',
            field=models.CharField(help_text='Raza de la Mascota', max_length=120),
        ),
    ]
