# Generated by Django 3.2.8 on 2021-12-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20211215_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='tipo_mascota',
            field=models.CharField(default=2, help_text='Tipo de  Mascota', max_length=120),
            preserve_default=False,
        ),
    ]
