# Generated by Django 3.2.8 on 2021-12-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_mascotas_tipo_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', models.CharField(help_text='Alimento para', max_length=120)),
                ('tipo_alimento', models.CharField(help_text='Tipo de alimento', max_length=120)),
                ('cantidad', models.IntegerField(help_text='Cantidad de alimento', max_length=120)),
                ('valor', models.FloatField(help_text='Valor del alimento', max_length=120)),
            ],
        ),
    ]
