# Generated by Django 3.2.8 on 2021-12-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_alimentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentos',
            old_name='comida',
            new_name='tipo_mascota',
        ),
    ]
